export { default as NavBar } from "./navbar/NavBar.jsx";
export { default as Menu } from "./menu/Menu.jsx";
export { default as Footer } from "./footer/Footer.jsx";
export { default as TopBox } from "./topBox/TopBox.jsx";
export { default as ChartBox } from "./chartBox/ChartBox.jsx";
export { default as BarChartBox } from "./barChartBox/BarChartBox.jsx";
export { default as PieChartBox } from "./pieChartBox/PieChartBox.jsx";
export { default as BigChartBox } from "./bigChartBox/BigChartBox.jsx";
export { default as DataTable } from "./dataTable/DataTable.jsx";
export { default as Add } from "./add/Add.jsx";
export { default as Single } from "./single/Single.jsx";
// export {default as } from ".";
// export {default as } from ".";